# Generated by Django 5.2 on 2025-05-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
